### ISSUE TITLE
Suggestion: SM3DL StageData Support

### ISSUE THREAD

**Issue by mariomadproductions** [Kinnay/SM3DW-Level-Editor#2]
I know it is a long shot, and you might not want to do it. But if the SM3DL StageData format is similar enough, could you add support for it?

I can supply some example files if you need them.

**Comment by kinnay** [comment]
I don't think Nintendo used the whole byml structure thing before the Wii U and the 3D model format is probably different too. If you send me some files, I'll look into it, but I'll only try to add support if the level and model formats are very similar or the same as in SM3DW.

edit: Actually, the byml format _is_ used in SM3DL: http://smsrealm.net/board/thread.php?id=131
The model format might still be completely different though.

**Comment by mariomadproductions** [comment]
I have sent you some example stuff from the normal EUR demo version of the game, on RVLution.net.

Every File Explorer can view the archives and models:
https://github.com/Gericom/EveryFileExplorer
http://florian.nouwt.com/EFE.zip

CGFX file format (uses BCMDL file ext in SM3DL)
http://florian.nouwt.com/wiki/index.php/CGFX_(File_Format)

**Comment by mariomadproductions** [comment]
I don't really need 3D model viewing support, or archive support, since I can extract the archive with another program.

Just a basic BYML viewer or editor would be great.
