### ISSUE TITLE
Suggestion: View or edit BYML data normally

### ISSUE THREAD

**Issue by mariomadproductions** [Kinnay/SM3DW-Level-Editor#3]
Like displaying it as a table, rather than a 3D model.
That means you could view other data, and view non-level BYML files.

**Comment by kinnay** [comment]
Chadderz made a tool, that does that: http://mk8.tockdom.com/wiki/Yamlconv

**Comment by mariomadproductions** [comment]
Okay. Thanks for the information.

**Comment by mariomadproductions** [comment]
Actually, it doesn't seem to work with SM3DW ones? Did you get it to work?

**Comment by kinnay** [comment]
Hm, you're right. It doesn't work. The problem with making an editor though, is that some byml files infinitely recurse themself. This is often done with looping 'paths' in levels. I might look into it when I have more time, but not now.
