### ISSUE TITLE
Trouble opening SM3DW-Level-Editor

### ISSUE THREAD

**Issue by Bri1101** [Kinnay/SM3DW-Level-Editor#7]
When I use python, SM3DW-Level-Editor doesn't want to open. How do I open it?

**Comment by kinnay** [comment]
What's the stack trace? Python always prints a nice error message when something goes wrong.

Make sure you're using the correct python version (2.7) and have installed the required modules (PyQt4 and PyOpenGL).

**Comment by Bri1101** [comment]
Ok, I have python version 2.7 and the required modules installed, but I don't know what to do next.

**Comment by kinnay** [comment]
Are you asking how to start a python program? Double-clicking main.py should work, but in that case you won't see the error message if something goes wrong. Another way is to start it from the command line: type `python main.py` after moving to the right directory with `cd`. Or you can start it from an IDE that supports python. IDLE has probably been installed automatically along with python.
